[project]
name = "mytechdocs"
version = "0.1.0"
description = "Documentation for my personal technology setup and workflows"
requires-python = ">=3.11"
dependencies = [
    "mdformat~=0.7.18",
]

[tool.mdformat]
wrap = 90
